---

- name: Backup IOS Devices
  hosts: all
  vars:
    ansible_become: true
    ansible_become_method: enable
    ansible_connection: network_cli
    ansible_network_os: ios
  gather_facts: no

  tasks:
    - name: gather router facts
      cisco.ios.facts:
    - name: Backup Device
      cisco.ios.ios_config:
        backup: yes
        backup_options:
         filename: backup.cfg
         dir_path: /home/msabo/
